[build]
builder = "DOCKERFILE"

[deploy]
startCommand = "vendor/bin/sail up --no-start && vendor/bin/sail up -d"

[env]
APP_ENV = "production"
APP_DEBUG = "false"
APP_URL = "https://<your-railway-subdomain>.railway.app"
DB_CONNECTION = "mysql"
DB_HOST = "mysql"
DB_PORT = "3306"
DB_DATABASE = "<your-db-name>"
DB_USERNAME = "root"
DB_PASSWORD = "<your-db-password>"
REDIS_HOST = "redis"
REDIS_PORT = "6379"
MEILISEARCH_HOST = "http://meilisearch:7700"
MAIL_MAILER = "smtp"
MAIL_HOST = "mailpit"
MAIL_PORT = "1025"
VITE_PORT = "5173"
WWWUSER = "1000"
WWWGROUP = "1000"

[[services]]
name = "laravel"
dockerfilePath = "vendor/laravel/sail/runtimes/8.4/Dockerfile"
context = "."
