[build]
builder = "NIXPACKS"

[deploy]
startCommand = "php artisan migrate --force && php artisan serve --host=0.0.0.0 --port=$PORT && npm run dev"

[env]
APP_ENV = "production"
APP_DEBUG = "true"  # Set to true temporarily for debugging
LOG_CHANNEL = "stderr"  # Important for Railway logging
